{{- if include "platform.isSelfContained" . }}
{{- if not .Values.tags.on_prem }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-blob-storage-key
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
data:
{{- if .Values.tags.gcp }}
  key.json: {{ .Values.gcp.serviceAccountKeyBase64 | quote }}
{{- else if .Values.tags.aws }}
# Note, while this Secret is configured empty, as we assume role on EKS level
  access_key: ""
  secret_key: ""
{{- else if .Values.tags.azure }}
  account_name: {{ .Values.blobStorage.azure.storageAccountName | b64enc | quote }}
  account_key: {{ .Values.blobStorage.azure.storageAccountKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}