apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-to-ssh-auth
  namespace: {{ include "platform.jobs.namespace.name" . }}
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          service: ssh-auth