{{- $standardLabels := include "platform.labels.standard" . }}
{{- $appName := include "platform.name" . }}
{{- $priorityClassName := include "platform.idleJobs.priorityClass.name" . }}
{{- $jobsNamespace := include "platform.jobs.namespace.name" . }}
{{- range .Values.kubernetes.nodePools }}
{{- if gt (.idleSize | int) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-idle-jobs-{{ .name | replace "_" "-" | lower }}
  labels:
{{ $standardLabels | indent 4 }}
    component: idle-jobs
spec:
  replicas: {{ .idleSize }}
  selector:
    matchLabels:
      app: {{ $appName }}
      release: {{ $.Release.Name }}
      component: idle-jobs
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: {{ .idleSize }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $appName }}
        release: {{ $.Release.Name }}
        component: idle-jobs
    spec:
      containers:
      - name: pause
        image: {{ $.Values.pauseImage.repository }}:{{ $.Values.pauseImage.tag }}
        resources:
          requests:
{{- if gt (.gpu | int) 0 }}
            cpu: "1"
            memory: 1Gi
            nvidia.com/gpu: {{ .gpu }}
{{- else }}
            cpu: {{ .cpu | quote }}
            memory: 1Gi
{{- end }}
          limits:
{{- if gt (.gpu | int) 0 }}
            cpu: "1"
            memory: 1Gi
            nvidia.com/gpu: {{ .gpu }}
{{- else }}
            cpu: {{ .cpu | quote }}
            memory: 1Gi
{{- end }}
      priorityClassName: {{ $priorityClassName }}
      tolerations:
      - key: ""
        operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ $.Values.kubernetes.labels.nodePool }}
                operator: In
                values:
                - {{ .name }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: {{ $.Values.jobs.label }}
                operator: Exists
            topologyKey: kubernetes.io/hostname
            namespaces:
            - {{ $jobsNamespace }}
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ $appName }}
              - key: release
                operator: In
                values:
                - {{ $.Release.Name }}
              - key: component
                operator: In
                values:
                - idle-jobs
            topologyKey: kubernetes.io/hostname
---
{{- end }}
{{- end }}
