{{- $imagesPrepull := .Values.kubernetes.imagesPrepull }}
{{- if .Values.kubernetes.imagesPrepull }}
{{- if gt (len .Values.kubernetes.imagesPrepull.images) 0 }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-images-prepull
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
    component: images-prepull
spec:
  selector:
    matchLabels:
      app: {{ include "platform.name" . }}
      release: {{ .Release.Name | quote }}
      component: images-prepull
  template:
    metadata:
      labels:
        app: {{ include "platform.name" . }}
        release: {{ .Release.Name | quote }}
        component: images-prepull
    spec:
      containers:
        - name: images-prepull
          image: {{ .Values.dockerImage.repository }}:{{ .Values.dockerImage.tag }}
          command:
            - /bin/sh
            - "-c"
            - |
              echo "docker pull interval : {{ $imagesPrepull.refreshInterval }}"
              while true
              do
              echo
              {{- range $imagesPrepull.images }}
              echo "$(date) - Pulling image : {{ .image }}"
              docker pull {{ .image }} || true
              {{- end }}
              echo "$(date) - docker pull - finished"
              sleep {{ $imagesPrepull.refreshInterval }}
              done
          volumeMounts:
            - name: docker
              mountPath: /var/run
      volumes:
        - name: docker
          hostPath:
            path: /var/run
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      nodeSelector:
        {{ .Values.jobs.label }}: "true"
{{- end }}
{{- end }}
