{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.imagePullSecret.name }}
  name: {{ .Values.imagePullSecret.name }}
{{- else }}
  name: {{ printf "%s-docker-config" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- end }}
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/dockerconfigjson
data:
{{- $credentials := .Values.imagePullSecret.credentials }}
{{- $dockerConfigJson := include "platform.dockerConfigJson" $credentials }}
  .dockerconfigjson: {{ $dockerConfigJson | b64enc | quote }}
{{- end }}
