{{- range .Values.storages }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ include "platform.storage.claimNameSuffix" .path }}
  namespace: {{ include "platform.jobs.namespace.name" $ }}
  labels: {{ include "platform.labels.standard" $ | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClassName | default "" | quote }}
  {{- if ne .type "kubernetes" }}
  volumeName: {{ $.Release.Name }}-{{ include "platform.storage.jobsVolumeNameSuffix" .path }}
  {{- end }}
{{- end }}
