{{- if .Values.dockerHubConfigSecret.create }}
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.dockerHubConfigSecret.name }}
  name: {{ .Values.dockerHubConfigSecret.name }}
{{- else }}
  name: {{ printf "%s-docker-hub-config" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- end }}
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
  namespace: {{ include "platform.jobs.namespace.name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/dockerconfigjson
data:
{{- $credentials := .Values.dockerHubConfigSecret.credentials }}
{{- $dockerConfigSecret := include "platform.dockerConfigSecret" $credentials }}
  .dockerconfigjson: {{ $dockerConfigSecret | b64enc | quote }}
{{- end }}
