{{- if ne .Values.storage.type "kubernetes" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "platform.storage.jobsPvName" . }}
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
{{- if eq .Values.storage.type "nfs" }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: {{ .Values.storage.nfs.path }}
    readOnly: false
{{- else if eq .Values.storage.type "azureFile" }}
  azureFile:
    secretName: {{ include "platform.azure.storageAccount.secretName" . }}
    secretNamespace: {{ .Release.Namespace }}
    shareName: {{ .Values.storage.azureFile.shareName }}
    readOnly: false
  mountOptions:
    - mfsymlinks
{{- else if eq .Values.storage.type "gcs" }}
  csi:
    driver: obs.csi.neu.ro
    volumeHandle: {{ .Values.storage.gcs.bucketName }}
    volumeAttributes:
      bucket: {{ .Values.storage.gcs.bucketName }}
      key_file: /accounts/key.json
      additional_args: --limit-ops-per-sec 0
{{- end }}
{{- end }}
