{{- if .Values.jobs.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "platform.jobs.namespace.name" . }}
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
{{- end }}