{{- range .Values.storages }}
{{- if ne .type "kubernetes" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-{{ include "platform.storage.jobsVolumeNameSuffix" .path }}
  labels: {{ include "platform.labels.standard" $ | nindent 4 }}
spec:
  capacity:
    storage: {{ .size }}
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  {{- if eq .type "nfs" }}
  nfs:
    server: {{ .nfs.server }}
    path: {{ .nfs.path }}
    readOnly: false
  {{- else if eq .type "smb" }}
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: {{ include "platform.smb.volumeHandle" . }}-jobs
    volumeAttributes:
      source: //{{ .smb.server }}/{{ .smb.shareName }}
    nodeStageSecretRef:
      name: {{ $.Release.Name }}-{{ include "platform.smb.secretNameSuffix" . }}
      namespace: {{ $.Release.Namespace }}
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
  {{- else if eq .type "azureFile" }}
  azureFile:
    secretName: {{ $.Release.Name }}-{{ include "platform.azure.storageAccount.secretNameSuffix" .path }}
    secretNamespace: {{ $.Release.Namespace }}
    shareName: {{ .azureFile.shareName }}
    readOnly: false
  mountOptions:
  - mfsymlinks
  {{- else if eq .type "gcs" }}
  csi:
    driver: obs.csi.neu.ro
    volumeHandle: {{ .gcs.bucketName }}
    volumeAttributes:
      bucket: {{ .gcs.bucketName }}
      key_file: /accounts/key.json
      additional_args: --limit-ops-per-sec 0
  {{- end }}
{{- end }}
{{- end }}
