apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform.jobs.serviceAccountName" . }}
  namespace: {{ include "platform.jobs.namespace.name" . }}
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
automountServiceAccountToken: false
