apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-storage
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClassName | default "" | quote }}
  {{- if ne .Values.storage.type "kubernetes" }}
  volumeName: {{ include "platform.storage.platformPvName" . }}
  {{- end }}
