apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: platform
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api/v1/blob
        backend:
          serviceName: platformobjectstorage
          servicePort: 8080
      - path: /api/v1/storage
        backend:
          serviceName: platformstorageapi
          servicePort: 8080
      - path: /api/v1/jobs
        backend:
          serviceName: platformmonitoringapi
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: platformingressfallback
  namespace: {{ include "platform.jobs.namespace.name" . }}
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.ingress.jobFallbackHost }}
  ports:
  - name: https
    port: 443
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: platformingressfallback
  namespace: {{ include "platform.jobs.namespace.name" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/preserve-host: "false"
    ingress.kubernetes.io/custom-response-headers: Cache-Control:no-store
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
spec:
  rules:
  - host: error-pages
    http:
      paths:
      - backend:
          serviceName: platformingressfallback
          servicePort: https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: platformglobal
  namespace: {{ include "platform.jobs.namespace.name" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/priority: "1"
    traefik.ingress.kubernetes.io/preserve-host: "false"
    ingress.kubernetes.io/custom-response-headers: Cache-Control:no-store
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
spec:
  backend:
    serviceName: platformingressfallback
    servicePort: https
