apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-storage
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: ""
  volumeName: {{ include "platform.storage.platformPvName" . }}