image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

tillerImage:
  repository: $DOCKER_SERVER/kubernetes-helm/tiller

kubectlImage:
  repository: $DOCKER_SERVER/bitnami/kubectl
  tag: 1.16

controller:
  retries: 3
  backoff: 60
  logLevel: INFO
  annotations: {}

platform:
  authUrl: https://staging.neu.ro
  ingressAuthUrl: https://staging.neu.ro
  configUrl: https://staging.neu.ro
  apiUrl: https://staging.neu.ro

# For backward compatibility with old clusters set to `false`
consulEnabled: true

consul:
  global:
    enabled: false
    image: $DOCKER_SERVER/hashicorp/consul:1.9.2

  nameOverride: consul
  fullnameOverride: consul

  server:
    enabled: true

    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "2"
        memory: "4Gi"

  ui:
    enabled: true
