image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

tillerImage:
  repository: $DOCKER_SERVER/kubernetes-helm/tiller

controller:
  retries: 3
  backoff: 60
  logLevel: INFO
  annotations: {}

platform:
  url: https://staging.neu.ro
