{{- if .Values.dockerHubConfigSecret.create }}
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.dockerHubConfigSecret.name }}
  name: {{ .Values.dockerHubConfigSecret.name }}
{{- else }}
  name: {{ printf "%s-docker-hub-config" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- end }}
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
{{- $credentials := .Values.dockerHubConfigSecret.credentials }}
{{- $dockerConfigJson := include "platform.dockerConfigJson" $credentials }}
  .dockerconfigjson: {{ $dockerConfigJson | b64enc | quote }}
{{- end }}
