{{- range .Values.nodePools }}
{{- if gt (.idleSize | int) 0 }}
{{- $name := .name | replace "_" "-" | lower }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-idle-nodes-{{ $name }}
  namespace: {{ include "platform.jobs.namespace.name" $ }}
  labels: {{ include "platform.labels.standard" $ | nindent 4 }}
    service: idle-nodes-$name
spec:
  replicas: {{ .idleSize }}
  selector:
    matchLabels:
      app: {{ include "platform.name" $ }}
      release: {{ $.Release.Name }}
      service: idle-nodes-$name
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: {{ .idleSize }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "platform.name" $ }}
        release: {{ $.Release.Name }}
        service: idle-nodes-$name
        platform.neuromation.io/idle: "true"
    spec:
      containers:
      {{- if $.Values.imagesPrepull.images }}
      - name: images-prepull
        image: {{ $.Values.crictlImage.repository }}:{{ $.Values.crictlImage.tag }}
        command: [bash]
        args:
          - -c
          - |
            if [[ -S /run/dockershim.sock ]]
            then
              RUNTIME_ENDPOINT=unix:///run/dockershim.sock
            fi

            if [[ -S /run/containerd/containerd.sock ]]
            then
              RUNTIME_ENDPOINT=unix:///run/containerd/containerd.sock
            fi

            if [[ -S /run/crio/crio.sock ]]
            then
              RUNTIME_ENDPOINT=unix:///run/crio/crio.sock
            fi

            echo "pull interval: {{ $.Values.imagesPrepull.refreshInterval }}"

            while true
            do
              echo
              {{- range $.Values.imagesPrepull.images }}
              echo "$(date) - pulling image: {{ .image }}"
              crictl -r $RUNTIME_ENDPOINT pull {{ .image }} || true
              echo "$(date) - pulled image: {{ .image }}"
              {{- end }}

              sleep {{ $.Values.imagesPrepull.refreshInterval }}
            done
      {{- else }}
      - name: pause
        image: {{ $.Values.pauseImage.repository}}:{{ $.Values.pauseImage.tag }}
      {{- end }}
        resources:
          requests:
{{- if gt (.gpu | int) 0 }}
            cpu: "1"
            memory: 1Gi
            nvidia.com/gpu: {{ .gpu }}
{{- else }}
            cpu: {{ .cpu | quote }}
            memory: 1Gi
{{- end }}
          limits:
{{- if gt (.gpu | int) 0 }}
            cpu: "1"
            memory: 1Gi
            nvidia.com/gpu: {{ .gpu }}
{{- else }}
            cpu: {{ .cpu | quote }}
            memory: 1Gi
{{- end }}
        volumeMounts:
          - name: host-run
            mountPath: /run
      volumes:
      - name: host-run
        hostPath:
          path: /run
      priorityClassName: {{ $.Release.Name }}-idle-node
      tolerations:
      - operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ $.Values.nodeLabels.nodePool }}
                operator: In
                values:
                - {{ .name }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: {{ $.Values.jobs.label }}
                operator: Exists
            topologyKey: kubernetes.io/hostname
            namespaces:
            - {{ include "platform.jobs.namespace.name" $ }}
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "platform.name" $ }}
              - key: release
                operator: In
                values:
                - {{ $.Release.Name }}
              - key: service
                operator: In
                values:
                - idle-nodes
            topologyKey: kubernetes.io/hostname
{{- end }}
{{- end }}
