apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "platformOperator.fullname" . }}-crds
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "0"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: update-crds
          image: {{ .Values.kubectlImage.repository }}:{{ .Values.kubectlImage.tag }}
          args: ["apply", "-f", "/etc/crds"]
          volumeMounts:
            - name: crds
              mountPath: /etc/crds
      volumes:
        - name: crds
          configMap:
            name: {{ include "platformOperator.fullname" . }}-crds
