apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platformOperator.fullname" . }}-crds
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
data:
{{ (.Files.Glob "crds/*").AsConfig | indent 2 }}
