apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: platforms.neuromation.io
  annotations:
    helm.sh/hook: crd-install
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    type: string
  - JSONPath: .status.retries
    name: Retries
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: neuromation.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    kind: Platform
    listKind: PlatformList
    plural: platforms
    singular: platform
    shortNames: []
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          description: >-
            APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: >-
            Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        status:
          type: object
          properties:
            phase:
              type: string
            conditions:
              type: array
              items:
                type: object
                required:
                - type
                - status
                - lastTransitionTime
                properties:
                  type:
                    type: string
                  status:
                    type: string
                    enum:
                    - "True"
                    - "False"
                    - Unknown
                  lastTransitionTime:
                    type: string
                    format: date-time
        spec:
          type: object
          required:
          - token
          - storage
          - monitoring
          properties:
            token:
              type: string
            kubernetes:
              type: object
              properties:
                standardStorageClassName:
                  type: string
                tpuIPv4CIDR:
                  type: string
                nodePorts:
                  type: object
                  required:
                  - kubelet
                  - http
                  - https
                  properties:
                    kubelet:
                      type: integer
                    http:
                      type: integer
                    https:
                      type: integer
                nodeLabels:
                  type: object
                  properties:
                    job:
                      type: string
                    nodePool:
                      type: string
                    accelerator:
                      type: string
                    preemptible:
                      type: string
                ingressController:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                ingressPublicIPs:
                  type: array
                  items:
                    type: string
                dockerConfigSecret:
                  type: object
                  properties:
                    create:
                      type: boolean
                    name:
                      type: string
                serviceAccount:
                  type: object
                  properties:
                    imagePullSecrets:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                        - name
                jobsNamespace:
                  type: object
                  properties:
                    create:
                      type: boolean
                    name:
                      type: string
            iam:
              type: object
              properties:
                gcp:
                  type: object
                  properties:
                    serviceAccountKeyBase64:
                      type: string
                aws:
                  type: object
                  properties:
                    roleArn:
                      type: string
                    s3RoleArn:
                      type: string
              oneOf:
              - properties:
                  gcp: {}
                required:
                - gcp
              - properties:
                  aws: {}
                required:
                - aws
            registry:
              type: object
              properties:
                azure:
                  type: object
                  required:
                  - url
                  - username
                  - password
                  properties:
                    url:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
                aws:
                  type: object
                  required:
                  - url
                  properties:
                    url:
                      type: string
                kubernetes:
                  type: object
                  required:
                  - persistence
                  properties:
                    persistence:
                      type: object
                      required:
                      - storageClassName
                      properties:
                        storageClassName:
                          type: string
                        size:
                          type: string
              oneOf:
              - properties:
                  azure: {}
                required:
                - azure
              - properties:
                  aws: {}
                required:
                - aws
              - properties:
                  kubernetes: {}
                required:
                - kubernetes
            storage:
              type: object
              properties:
                nfs:
                  type: object
                  required:
                  - server
                  properties:
                    server:
                      type: string
                    path:
                      type: string
                gcs:
                  type: object
                  required:
                  - bucket
                  properties:
                    bucket:
                      type: string
                azureFile:
                  type: object
                  required:
                  - storageAccountName
                  - storageAccountKey
                  - shareName
                  properties:
                    storageAccountName:
                      type: string
                    storageAccountKey:
                      type: string
                    shareName:
                      type: string
                kubernetes:
                  type: object
                  required:
                  - persistence
                  properties:
                    persistence:
                      type: object
                      required:
                      - storageClassName
                      properties:
                        storageClassName:
                          type: string
                        size:
                          type: string
              oneOf:
              - properties:
                  nfs: {}
                required:
                - nfs
              - properties:
                  gcs: {}
                required:
                - gcs
              - properties:
                  azureFile: {}
                required:
                - azureFile
              - properties:
                  kubernetes: {}
                required:
                - kubernetes
            blobStorage:
              type: object
              properties:
                azure:
                  type: object
                  required:
                  - storageAccountName
                  - storageAccountKey
                  properties:
                    storageAccountName:
                      type: string
                    storageAccountKey:
                      type: string
                kubernetes:
                  type: object
                  required:
                  - persistence
                  properties:
                    persistence:
                      type: object
                      required:
                      - storageClassName
                      properties:
                        storageClassName:
                          type: string
                        size:
                          type: string
              oneOf:
              - properties:
                  azure: {}
                required:
                - azure
              - properties:
                  kubernetes: {}
                required:
                - kubernetes
            monitoring:
              type: object
              required:
              - logs
              - metrics
              properties:
                logs:
                  type: object
                  required:
                  - blobStorage
                  properties:
                    blobStorage:
                      type: object
                      required:
                      - bucket
                      properties:
                        bucket:
                          type: string
                metrics:
                  type: object
                  properties:
                    retentionTime:
                      type: string
                    blobStorage:
                      type: object
                      required:
                      - bucket
                      properties:
                        bucket:
                          type: string
                    kubernetes:
                      type: object
                      required:
                      - persistence
                      properties:
                        persistence:
                          type: object
                          required:
                          - storageClassName
                          properties:
                            storageClassName:
                              type: string
                            size:
                              type: string
                  oneOf:
                  - properties:
                      blobStorage: {}
                    required:
                    - blobStorage
                  - properties:
                      kubernetes: {}
                    required:
                    - kubernetes
            disks:
              type: object
              properties:
                kubernetes:
                  type: object
                  properties:
                    persistence:
                      type: object
                      required:
                      - storageClassName
                      properties:
                        storageClassName:
                          type: string
