apiVersion: v2
name: platform
description: Neu.ro platform services
kubeVersion: ">= 1.16-0"
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: traefik
    version: "25.0.0"
    repository: https://helm.traefik.io/traefik
    condition: traefikEnabled
  - name: acme
    version: "1.3.2"
    repository: https://neuro-inc.github.io/helm-charts
    condition: acmeEnabled
  - name: docker-registry
    version: "1.9.2"
    repository: https://charts.helm.sh/stable
    condition: dockerRegistryEnabled
  - name: minio
    version: "5.0.33"
    repository: https://charts.helm.sh/stable
    condition: minioEnabled
  - name: minio-gateway
    version: "0.2.3"
    repository: https://neuro-inc.github.io/helm-charts
    condition: minioGatewayEnabled
  - name: platform-storage
    version: "25.5.1"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-registry
    version: "24.11.1"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-monitoring
    version: "25.5.2"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-container-runtime
    version: "23.7.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-secrets
    version: "25.5.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-reports
    version: "25.2.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
    condition: platformReportsEnabled
  - name: platform-disks
    version: "23.7.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-api-poller
    version: "25.2.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-buckets
    version: "23.7.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-metadata
    version: "25.5.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
  - name: pgo
    alias: apps-postgres-operator
    version: "5.6.1"
    repository: oci://ghcr.io/neuro-inc/helm-charts
    condition: appsPostgresOperatorEnabled
  - name: spark-operator
    version: "2.1.0"
    repository: "https://kubeflow.github.io/spark-operator"
    condition: appsSparkOperatorEnabled
  - name: keda
    version: "2.16.1"
    repository: https://kedacore.github.io/charts
    condition: appsKedaEnabled
  - name: loki
    version: "6.29.0"
    repository: https://grafana.github.io/helm-charts
    condition: lokiEnabled
  - name: alloy
    version: "1.0.1"
    repository: https://grafana.github.io/helm-charts
    condition: alloyEnabled
