apiVersion: v2
name: platform
description: Neu.ro platform services
version: $CHART_VERSION
appVersion: $APP_VERSION
dependencies:
  - name: traefik
    version: "1.85.1"
    repository: https://charts.helm.sh/stable
    condition: traefikEnabled
  - name: docker-registry
    version: "1.9.2"
    repository: https://charts.helm.sh/stable
    condition: dockerRegistryEnabled
  - name: minio
    version: "5.0.33"
    repository: https://charts.helm.sh/stable
    condition: minioEnabled
  - name: platform-storage
    version: "21.12.3"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-registry
    version: "21.12.3"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-monitoring
    version: "21.12.4"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-container-runtime
    version: "21.11.3"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-secrets
    version: "21.12.5"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-reports
    version: "21.12.5"
    repository: oci://ghcr.io/neuro-inc/helm-charts
    condition: platformReportsEnabled
  - name: platform-disks
    version: "21.12.6"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-api-poller
    version: "21.12.10"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-buckets
    version: "21.12.6"
    repository: oci://ghcr.io/neuro-inc/helm-charts

  # Deprecated, left for backward compatibility with old clusters
  - name: consul
    version: "3.9.6"
    repository: https://charts.helm.sh/stable
    condition: consulEnabled
