apiVersion: v2
name: platform
description: Neu.ro platform services
kubeVersion: ">= 1.16-0"
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: traefik
    version: "10.14.1"
    repository: https://helm.traefik.io/traefik
    condition: traefikEnabled
  - name: acme
    version: "1.0.7"
    repository: https://neuro-inc.github.io/helm-charts
    condition: acmeEnabled
  - name: docker-registry
    version: "1.9.2"
    repository: https://charts.helm.sh/stable
    condition: dockerRegistryEnabled
  - name: minio
    version: "5.0.33"
    repository: https://charts.helm.sh/stable
    condition: minioEnabled
  - name: platform-storage
    version: "22.4.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-registry
    version: "22.5.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-monitoring
    version: "22.4.2"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-container-runtime
    version: "22.2.1"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-secrets
    version: "22.2.3"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-reports
    version: "22.6.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
    condition: platformReportsEnabled
  - name: platform-disks
    version: "22.5.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-api-poller
    version: "22.4.2"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-buckets
    version: "22.5.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
