apiVersion: v2
name: platform
description: Neu.ro platform services
version: $CHART_VERSION
appVersion: $APP_VERSION
dependencies:
  - name: traefik
    version: "10.14.1"
    repository: https://helm.traefik.io/traefik
    condition: traefikEnabled
  - name: acme
    version: "1.0.2"
    repository: https://neuro-inc.github.io/helm-charts
    condition: acmeEnabled
  - name: docker-registry
    version: "1.9.2"
    repository: https://charts.helm.sh/stable
    condition: dockerRegistryEnabled
  - name: minio
    version: "5.0.33"
    repository: https://charts.helm.sh/stable
    condition: minioEnabled
  - name: platform-storage
    version: "22.2.0"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-registry
    version: "22.2.37"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-monitoring
    version: "22.2.1"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-container-runtime
    version: "21.11.3"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-secrets
    version: "22.2.2"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-reports
    version: "22.2.3"
    repository: oci://ghcr.io/neuro-inc/helm-charts
    condition: platformReportsEnabled
  - name: platform-disks
    version: "22.2.2"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-api-poller
    version: "22.2.1"
    repository: oci://ghcr.io/neuro-inc/helm-charts
  - name: platform-buckets
    version: "22.2.1"
    repository: oci://ghcr.io/neuro-inc/helm-charts

  # Deprecated, left for backward compatibility with old clusters
  - name: consul
    version: "3.9.6"
    repository: https://charts.helm.sh/stable
    condition: consulEnabled
