apiVersion: v2
name: platform
description: Neu.ro platform services
version: $CHART_VERSION
appVersion: $APP_VERSION
dependencies:
  - name: traefik
    version: "1.85.1"
    repository: https://charts.helm.sh/stable
    condition: traefikEnabled
  - name: docker-registry
    version: "1.9.2"
    repository: https://charts.helm.sh/stable
    condition: dockerRegistryEnabled
  - name: minio
    version: "5.0.33"
    repository: https://charts.helm.sh/stable
    condition: minioEnabled
  - name: platform-storage
    version: "21.11.3"
    repository: oci://ghcr.io/neuro-inc/helm-charts/platform-storage
  - name: platform-registry
    version: "21.11.4"
    repository: oci://ghcr.io/neuro-inc/helm-charts/platform-registry
  - name: platform-monitoring
    version: "21.11.5"
    repository: oci://ghcr.io/neuro-inc/helm-charts/platform-monitoring
  - name: platform-container-runtime
    version: "21.11.3"
    repository: oci://ghcr.io/neuro-inc/helm-charts/platform-container-runtime
  - name: platform-secrets
    version: "21.11.26"
    repository: oci://ghcr.io/neuro-inc/helm-charts/platform-secrets
  - name: platform-reports
    version: "21.11.5"
    repository: oci://ghcr.io/neuro-inc/helm-charts/platform-reports
  - name: platform-disks
    version: "21.11.5"
    repository: oci://ghcr.io/neuro-inc/helm-charts/platform-disks
  - name: platform-api-poller
    version: "21.11.9"
    repository: oci://ghcr.io/neuro-inc/helm-charts/platform-api-poller
  - name: platform-buckets
    version: "21.11.4"
    repository: oci://ghcr.io/neuro-inc/helm-charts/platform-buckets

  # Deprecated, left for backward compatibility with old clusters
  - name: consul
    version: "3.9.6"
    repository: https://charts.helm.sh/stable
    condition: consulEnabled
