pauseImage:
  repository: $DOCKER_SERVER/google_containers/pause
  tag: "3.0"

alpineImage:
  repository: $DOCKER_SERVER/alpine
  tag: latest

crictlImage:
  repository: $DOCKER_SERVER/crictl
  tag: "1.22.0"

kubectlImage:
  repository: $DOCKER_SERVER/bitnami/kubectl
  tag: "1.16"

serviceToken: ""

nodePools: []

nodeLabels:
  nodePool: platform.neuromation.io/nodepool
  job: platform.neuromation.io/job

inotify:
  maxWatchers: 65536

nvidiaGpuDriver:
  image:
    repository: $DOCKER_SERVER/nvidia/k8s-device-plugin
    tag: 1.0.0-beta6

imagesPrepull:
  refreshInterval: 1h
  images: []

dockerConfigSecret:
  create: false
  name: ""
  # credentials:
  #   url: https://gcr.io
  #   email: username@email.com
  #   username: username
  #   password: password


dockerHubConfigSecret:
  create: false
  name: ""
  # credentials:
  #   url: https://index.docker.io/v1/
  #   email: username@email.com
  #   username: username
  #   password: password


standardStorageClass:
  create: true
  name: ""

ingress: {}
  # jobFallbackHost: default.jobs-dev.neu.ro
  # registryHost: registry.default.org.neu.ro

jobs:
  namespace:
    create: true
    name: ""
  label: platform.neuromation.io/job

idleJobs: []

storage: []
# - type: kubernetes # nfs, gcs, azureFile
#   path:
#   size: 10Gi

#   storageClassName: ""

#   nfs:
#     server: nfs-server
#     path: /path

#   azureFile:
#     storageAccountName: storage-account-name
#     storageAccountKey: storage-account-key
#     shareName: share

#   gcs:
#     bucketName: bucket

disks:
  storageClass:
    create: true
    name: ""

traefikEnabled: true
consulEnabled: false
dockerRegistryEnabled: false
minioEnabled: false

tags:
  gcp: false
  aws: false
  azure: false
  on_prem: false
