{{- range .Values.idleJobs }}
{{- if gt (.count | int) 0 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-idle-jobs-{{ .name | lower }}
  namespace: {{ include "platform.jobs.namespace.name" $ }}
  labels: {{ include "platform.labels.standard" $ | nindent 4 }}
    service: idle-jobs-{{ .name | lower }}
spec:
  replicas: {{ .count }}
  selector:
    matchLabels:
      app: {{ include "platform.name" $ }}
      release: {{ $.Release.Name }}
      service: idle-jobs-{{ .name | lower }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: {{ .count }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "platform.name" $ }}
        release: {{ $.Release.Name }}
        service: idle-jobs-{{ .name | lower }}
        platform.neuromation.io/idle: "true"
    spec:
      containers:
      - name: job
        image: {{ .image | quote }}
        {{- if .command }}
        command: {{ toYaml .command | nindent 8 }}
        {{- end }}
        {{- if .args }}
        args: {{ toYaml .args | nindent 8 }}
        {{- end }}
        resources:
          requests: {{ toYaml .resources | nindent 12 }}
          limits: {{ toYaml .resources | nindent 12 }}
        env:
        - name: NEURO_CLUSTER
          value: {{ $.Values.clusterName }}
        - name: NEURO_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- if .env }}
        envFrom:
        - secretRef:
            name: {{ $.Release.Name }}-idle-jobs-secret-{{ .name | lower }}
        {{- end }}
      priorityClassName: {{ $.Release.Name }}-idle-job
      tolerations:
      - key: ""
        operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ $.Values.nodeLabels.job | quote }}
                operator: Exists
              {{- range $key, $value := .nodeSelector }}
              - key: {{ $key | quote }}
                operator: In
                values:
                - {{ $value | quote }}
              {{- end }}
      {{- if .imagePullSecrets }}
      imagePullSecrets: {{ toYaml .imagePullSecrets | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}
