apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-idle-egress
  namespace: {{ include "platform.jobs.namespace.name" . }}
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      platform.neuromation.io/idle: "true"
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
