apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "platform.idleJobs.priorityClass.name" . }}
  labels:
{{ include "platform.labels.standard" . | indent 4 }}
value: -1
globalDefault: false
