{{- if and .Values.traefik.acme.enabled .Values.traefik.acme.staging }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-acme-ca-cert
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
    service: acme-ca-cert
spec:
  selector:
    matchLabels:
      app: {{ include "platform.name" . }}
      release: {{ .Release.Name }}
      service: acme-ca-cert
  template:
    metadata:
      labels:
        app: {{ include "platform.name" . }}
        release: {{ .Release.Name }}
        service: acme-ca-cert
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      initContainers:
      - name: acme-ca-cert
        image: {{ .Values.alpineImage.repository }}:{{ .Values.alpineImage.tag }}
        command:
        - sh
        - -c
        - |
          mkdir -p /etc/docker/certs.d/{{ .Values.ingress.registryHost }}
          wget -O /etc/docker/certs.d/{{ .Values.ingress.registryHost }}/ca.crt https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem
          echo "Letsencrypt staging certificate installed"
        volumeMounts:
        - mountPath: /etc/docker/certs.d
          name: certs
      containers:
      - name: pause
        image: {{ .Values.pauseImage.repository }}:{{ .Values.pauseImage.tag }}
      volumes:
      - name: certs
        hostPath:
          path: /etc/docker/certs.d
{{- end }}
