apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-acme-certs
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
    service: acme-certs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-acme-certs
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
    service: acme-certs
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-acme-certs
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
    service: acme-certs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-acme-certs
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-acme-certs
  namespace: {{ .Release.Namespace }}
