{{- $kubernetesEndpoint := lookup "v1" "Endpoints" "default" "kubernetes" -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-to-kubernetes-api
  namespace: {{ include "platform.jobs.namespace.name" . }}
  labels:
    {{- include "platform.labels.standard" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    {{- range $kubernetesEndpoint.subsets }}
    - to:
        {{- range .addresses }}
        - ipBlock:
            cidr: {{ .ip }}/32
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: TCP
          port: {{ .port }}
        {{- end }}
    {{- end }}
