{{- if .Values.jobs.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "platform.jobs.namespace.name" . }}
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
{{- end }}
