{{- if .Values.minioEnabled -}}
{{- $ingressApiIsStable := eq (include "k8s.ingress.isStable" .) "true" -}}
apiVersion: {{ include "k8s.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-minio
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
  annotations:
    {{- if not $ingressApiIsStable }}
    kubernetes.io/ingress.class: traefik
    {{- end }}
spec:
  {{- if $ingressApiIsStable }}
  ingressClassName: traefik
  {{- end }}
  rules:
  - host: {{ .Values.ingress.minioHost }}
    http:
      paths:
      - path: /
        {{- if $ingressApiIsStable }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if $ingressApiIsStable }}
          service:
            name: {{ $.Release.Name }}-minio
            port:
              name: http
          {{- else }}
          serviceName: {{ $.Release.Name }}-minio
          servicePort: http
          {{- end }}
{{- end }}
