apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssl-cert
  {{- if .Values.acme.enabled }}
  annotations:
    helm.sh/hook: pre-install
  {{- else }}
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  cert.crt: {{ .Values.ssl.cert | quote }}
  cert.key: {{ .Values.ssl.key | quote }}
