apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-token
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.serviceToken | b64enc | quote }}
