{{- if .Values.appsExternalSecretsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.appRole.secretRef.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  {{ .Values.vault.appRole.secretRef.key }}: {{ .Values.vault.appRole.secretId | b64enc | quote }}
{{- end }}
