{{- range .Values.storages }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ include "platform.storage.claimNameSuffix" .path }}
  labels: {{ include "platform.labels.standard" $ | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClassName | default "" | quote }}
  volumeName: {{ $.Release.Name }}-{{ include "platform.storage.platformVolumeNameSuffix" .path }}
{{- end }}
