apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-cors
  labels:
    {{- include "platform.labels.standard" . | nindent 4 }}
    service: traefik
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - HEAD
      - OPTIONS
    accessControlAllowHeaders:
      - authorization
      - accept
      - accept-language
      - content-language
      - upgrade
      - connection
      - sec-websocket-accept
      - sec-websocket-protocol
      - sec-websocket-version
      - sec-websocket-extensions
      - sec-websocket-key
      - sec-websocket-key1
      - last-event-id
      - content-type
      - x-requested-with
      - x-amz-content-sha256
      - x-amz-security-token
      - x-amz-date
      - x-amz-user-agent
      - amz-sdk-invocation-id
      - amz-sdk-request
    {{- with .Values.ingress.cors.originList }}
    accessControlAllowOriginList:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.ingress.cors.originListRegex }}
    accessControlAllowOriginListRegex:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    accessControlMaxAge: 100
    addVaryHeader: true
