{{- if .Values.traefikEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-traefik-dynamic-config
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
    service: traefik
data:
  config.yaml: |
    tls:
      certificates:
      - certFile: /etc/certs/cert.crt
        keyFile: /etc/certs/cert.key
      stores:
        default:
          defaultCertificate:
            certFile: /etc/certs/cert.crt
            keyFile: /etc/certs/cert.key
{{- end }}
