{{- if and .Values.ssl.cert .Values.ssl.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssl-cert
  {{- if .Values.acmeEnabled }}
  annotations:
    helm.sh/hook: pre-install
  {{- else }}
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  tls.crt: {{ .Values.ssl.cert | quote }}
  tls.key: {{ .Values.ssl.key | quote }}
{{- end }}
