{{- if .Values.platform.standalone }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "platformOperator.platformApi.fullname" . }}-migrations
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
    service: platform-api
  {{- if .Release.IsUpgrade }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  {{- end }}
spec:
  {{- if .Release.IsInstall }}
  backoffLimit: 6
  {{- end }}
  template:
    spec:
      {{- if .Release.IsInstall }}
      restartPolicy: OnFailure
      {{- else }}
      restartPolicy: Never
      {{- end }}
      containers:
      - name: run-migrations
        {{- with .Values.platformApi.image }}
        image: {{ .repository }}:{{ .tag }}
        {{- end }}
        command: ["alembic", "upgrade", "head"]
        env:
        - name: NP_DB_POSTGRES_DSN
          valueFrom:
            secretKeyRef:
              name: {{ include "platformOperator.postgresqlConfig.fullname" . }}-secrets
              key: platform-api-migrations-runner-dsn
      priorityClassName: {{ .Release.Namespace }}-services
{{- end }}
