{{- if .Values.platform.standalone }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "platformOperator.platformConfig.fullname" . }}
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
    service: platform-config
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api/v1/clusters
        backend:
          serviceName: {{ include "platformOperator.platformConfig.fullname" . }}
          servicePort: http
{{- end }}
