{{- if .Values.platform.standalone }}
{{- $ingressApiIsStable := eq (include "k8s.ingress.isStable" .) "true" -}}
apiVersion: {{ include "k8s.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "platformOperator.platformConfig.fullname" . }}
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
    service: platform-config
  {{- if not $ingressApiIsStable }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
  {{- end }}
spec:
  {{- if $ingressApiIsStable }}
  ingressClassName: traefik
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api/v1/clusters
        {{- if $ingressApiIsStable }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if $ingressApiIsStable }}
          service:
            name: {{ include "platformOperator.platformConfig.fullname" . }}
            port:
              name: http
          {{- else }}
          serviceName: {{ include "platformOperator.platformConfig.fullname" . }}
          servicePort: http
          {{- end }}
{{- end }}
