{{- if .Values.platform.standalone }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformOperator.platformConfig.fullname" . }}
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
    service: platform-config
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: {{ include "platformOperator.name" . }}
    release: {{ .Release.Name }}
    service: platform-config
{{- end }}
