{{- if .Values.platform.standalone }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platformOperator.platformConfig.fullname" . }}-clusters
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
    service: platform-config
data:
  cluster.json: |
{{ tpl (.Files.Get "files/cluster.json.tpl") . | trim | indent 4 }}
  clusters.json: |
    [
{{ tpl (.Files.Get "files/cluster.json.tpl") . | trim | indent 6 }}
    ]
{{- end }}
