{{- if .Values.platform.standalone }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platformOperator.postgresqlConfig.fullname" . }}-secrets
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresqlConfig.postgresqlPassword | b64enc | quote }}
  platform-api-migrations-runner-dsn: {{ include "platformOperator.postgresqlConfig.platformApi.migrationsRunnerDsn" . | b64enc | quote }}
  platform-api-service-dsn: {{ include "platformOperator.postgresqlConfig.platformApi.serviceDsn" . | b64enc | quote }}
{{- end }}
