{{- if .Values.standalone }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platformOperator.postgresqlInitScript.fullname" . }}
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
data:
  init_db.sh: |
{{ include "postgres-db-init-script.script" . | indent 4 }}
{{- end }}
