apiVersion: v2
kubeVersion: ">= 1.16-0"
version: $CHART_VERSION
appVersion: $APP_VERSION
name: platform-operator
description: Neu.ro platform operator
dependencies:
  - name: consul
    version: "0.29.0"
    repository: https://helm.releases.hashicorp.com
    condition: consulEnabled
  - name: postgresql
    version: "10.13.11"
    repository: https://charts.bitnami.com/bitnami
    condition: standalone
  - name: postgres-db-init-script
    version: "1.0.5"
    repository: https://neuro-inc.github.io/helm-charts
