apiVersion: v2
kubeVersion: ">= 1.16-0"
version: 1.0.0
appVersion: 1.0.0
name: platform-operator
description: Neu.ro platform operator
dependencies:
  - name: postgresql
    version: "10.13.11"
    repository: https://charts.bitnami.com/bitnami
    condition: platform.standalone
  - name: postgres-db-init-script
    version: "1.0.8"
    repository: https://neuro-inc.github.io/helm-charts
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
