image:
  repository: $IMAGE_REPO
  tag: $IMAGE_TAG

imagePullSecrets: []

serviceAccount:
  annotations: {}

kubectlImage:
  repository: ghcr.io/neuro-inc/kubectl
  tag: 1.16

nginxImage:
  repository: ghcr.io/neuro-inc/nginx
  tag: latest

controller:
  securityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    fsGroupChangePolicy: "OnRootMismatch"
  retries: 3
  backoff: 60
  logLevel: INFO
  annotations: {}

platform:
  standalone: false
  authUrl: https://api.apolo.us
  ingressAuthUrl: https://api.apolo.us
  configUrl: https://api.apolo.us
  apiUrl: https://api.apolo.us
  appsUrl: https://api.apolo.us
  adminUrl: https://api.apolo.us
  notificationsUrl: https://api.apolo.us
  eventsUrl: https://api.apolo.us
