standalone: true

consul:
  server:
    replicas: 1

platform:
  configUrl: http://platform-config:8080
  apiUrl: http://platform-api:8080
  authUrl: "-"
  ingressAuthUrl: "-"
  adminUrl: "-"

ingress:
  host: neu.ro.local

minio:
  username: minio_access_key
  password: minio_secret_key

postgresqlConfig:
  nameOverride: postgresql-config
  fullnameOverride: postgresql-config

  host: postgresql
  port: 5432

  postgresqlUsername: postgres
  postgresqlPassword: postgres

  platformApiDatabase: platform_api
  platformApiMigrationsRunnerUsername: platform_api_migrations_runner
  platformApiMigrationsRunnerPassword: platform_api_migrations_runner
  platformApiServiceUsername: platform_api_service
  platformApiServicePassword: platform_api_service

postgresqlInitScript:
  nameOverride: postgresql-init-script
  fullnameOverride: postgresql-init-script

postgresql:
  nameOverride: postgresql
  fullnameOverride: postgresql

  image:
    repository: ghcr.io/neuro-inc/postgresql

  postgresqlUsername: postgres

  existingSecret: postgresql-config-secrets

  initdbScriptsConfigMap: postgresql-init-script

  extraEnv:
  - name: NP_POSTGRES_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql-config-secrets
        key: postgresql-password
  - name: NP_MIGRATIONS_RUNNER_DSN
    valueFrom:
      secretKeyRef:
        name: postgresql-config-secrets
        key: platform-api-migrations-runner-dsn
  - name: NP_SERVICE_DSN
    valueFrom:
      secretKeyRef:
        name: postgresql-config-secrets
        key: platform-api-service-dsn

  persistence:
    # storageClass:
    size: 50Gi

platformConfig:
  nameOverride: platform-config
  fullnameOverride: platform-config

  resourcePools: []
  resourcePresets: []

platformApi:
  nameOverride: platform-api
  fullnameOverride: platform-api

  image:
    repository: ghcr.io/neuro-inc/platformapi
    tag: 21.12.10

  oauth:
    authUrl: http://keycloak-http:80/auth/realms/neu.ro/protocol/openid-connect/auth
    tokenUrl: http://keycloak-http:80/auth/realms/neu.ro/protocol/openid-connect/token
    logoutUrl: http://keycloak-http:80/auth/realms/neu.ro/protocol/openid-connect/logout
    clientId: neuro-client
    audience: https://neu.ro
    successRedirectUrl: http://platform-ingress-auth:8080/oauth/login
    headlessCallbackUrl: http://platform-ingress-auth:8080/oauth/show-code

  enforcerRetentionDelayDays: 30
