image:
  repository: $IMAGE_REPO
  tag: $IMAGE_TAG

imagePullSecrets: []

serviceAccount:
  annotations: {}

kubectlImage:
  repository: ghcr.io/neuro-inc/kubectl
  tag: 1.16

nginxImage:
  repository: ghcr.io/neuro-inc/nginx
  tag: latest

controller:
  retries: 3
  backoff: 60
  logLevel: INFO
  annotations: {}

platform:
  standalone: false
  authUrl: https://staging.neu.ro
  ingressAuthUrl: https://staging.neu.ro
  configUrl: https://staging.neu.ro
  apiUrl: https://staging.neu.ro
  adminUrl: https://staging.neu.ro
  servicesPodsPriorityClass:
    create: true
    className: platform-services
    classValue: 1000
