{{- if .Values.nvidiaDCGMExporter.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-dcgm-exporter
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
    service: nvidia-dcgm-exporter
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: {{ include "platform.name" . }}
      release: {{ .Release.Name }}
      service: nvidia-dcgm-exporter
  template:
    metadata:
      labels:
        app: {{ include "platform.name" . }}
        release: {{ .Release.Name }}
        service: nvidia-dcgm-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodeLabels.gpu }}
                    operator: Exists
      tolerations:
        # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
        # This, along with the annotation above marks this pod as a critical add-on.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: nvidia-dcgm-exporter
          {{- with .Values.nvidiaDCGMExporter.image }}
          image: {{ .repository }}:{{ .tag }}
          {{- end }}
          env:
            - name: DCGM_EXPORTER_COLLECTORS
              value: /etc/dcgm-exporter/custom/counters.csv
            - name: DCGM_EXPORTER_LISTEN
              value: ":9400"
            - name: DCGM_EXPORTER_KUBERNETES
              value: "true"
          ports:
            - name: metrics
              containerPort: 9400
              hostPort: 9400
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: pod-gpu-resources
              readOnly: true
              mountPath: /var/lib/kubelet/pod-resources
            - name: dcgm-counters
              readOnly: true
              mountPath: /etc/dcgm-exporter/custom
      volumes:
        - name: pod-gpu-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources
        - name: dcgm-counters
          configMap:
            name: nvidia-dcgm-counters
{{- end }}
