{{- if and .Values.nvidiaDCGMExporter.enabled .Values.nvidiaDCGMExporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-exporter
  labels: {{ include "platform.labels.standard" . | nindent 4 }}
    service: nvidia-dcgm-exporter
    platform.apolo.us/scrape-metrics: "true"
spec:
  selector:
    matchLabels:
      app: {{ include "platform.name" . }}
      release: {{ .Release.Name | quote }}
      service: nvidia-dcgm-exporter
  endpoints:
  - port: metrics
    path: /metrics
    honorLabels: true
    interval: 15s
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
{{- end }}
