apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformOperator.fullname" . }}-controller
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
    service: platform-operator-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "platformOperator.name" . }}
      release: {{ .Release.Name }}
      service: platform-operator-controller
  template:
    metadata:
      labels:
        app: {{ include "platformOperator.name" . }}
        release: {{ .Release.Name }}
        service: platform-operator-controller
{{- if .Values.controller.annotations }}
      annotations:
{{ toYaml .Values.controller.annotations | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ include "platformOperator.fullname" . }}
      automountServiceAccountToken: true
      containers:
      - name: controller
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - --standalone
        - --namespace={{ .Release.Namespace }}
        - --liveness=http://0.0.0.0:8080/healthz
        - --verbose
        - --log-format=full
        env:
        - name: NP_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NP_CONTROLLER_LOG_LEVEL
          value: {{ .Values.logLevel | default "INFO" }}
        - name: NP_CONTROLLER_RETRIES
          value: {{ .Values.controller.retries | quote }}
        - name: NP_CONTROLLER_BACKOFF
          value: {{ .Values.controller.backoff | quote }}
        - name: NP_KUBE_VERSION
          value: {{ .Capabilities.KubeVersion.Version | toString | quote }}
        - name: NP_KUBE_URL
          value: https://kubernetes.default.svc
        - name: NP_KUBE_CERT_AUTHORITY_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NP_KUBE_AUTH_TYPE
          value: token
        - name: NP_KUBE_AUTH_TOKEN_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: HELM_EXPERIMENTAL_OCI
          value: "1"
        - name: NP_HELM_PLATFORM_CHART_VERSION
          value: {{ .Chart.Version | quote }}
        - name: NP_HELM_OBS_CSI_DRIVER_CHART_VERSION
          value: "1.0.5"
        - name: NP_PLATFORM_AUTH_URL
          value: {{ .Values.platform.authUrl | quote }}
        - name: NP_PLATFORM_INGRESS_AUTH_URL
          value: {{ .Values.platform.ingressAuthUrl | quote }}
        - name: NP_PLATFORM_CONFIG_URL
          value: {{ .Values.platform.configUrl | quote }}
        - name: NP_PLATFORM_ADMIN_URL
          value: {{ .Values.platform.adminUrl | quote }}
        - name: NP_PLATFORM_API_URL
          value: {{ .Values.platform.apiUrl | quote }}
        - name: NP_PLATFORM_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: NP_PLATFORM_LOCK_SECRET_NAME
          value: {{ include "platformOperator.fullname" . }}-lock
        - name: NP_ACME_CA_STAGING_PATH
          value: /etc/platform/ca_staging.pem
        {{- if .Values.platform.standalone }}
        - name: NP_STANDALONE
          value: "true"
        {{- end }}
        ports:
        - name: liveness-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: liveness-port
          initialDelaySeconds: 10
          periodSeconds: 3
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
