apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platformOperator.fullname" . }}-lock
  labels:
    app: {{ include "platformOperator.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
