apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platformOperator.fullname" . }}
  labels:
{{ include "platformOperator.labels.standard" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "platformOperator.fullname" . }}
  labels:
{{ include "platformOperator.labels.standard" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "platformOperator.fullname" . }}
  namespace: {{ .Release.Namespace }}
