apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Namespace }}-services
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
value: 1000
globalDefault: false
