{{- if .Values.platform.servicesPodsPriorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.platform.servicesPodsPriorityClass.name }}
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
value: {{ .Values.platform.servicesPodsPriorityClass.value }}
globalDefault: false
{{- end }}
