apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platformOperator.fullname" . }}
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
