apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platformOperator.fullname" . }}-upgrade
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "platformOperator.fullname" . }}-upgrade
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "platformOperator.fullname" . }}-upgrade
  labels: {{ include "platformOperator.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "platformOperator.fullname" . }}-upgrade
subjects:
- kind: ServiceAccount
  name: {{ include "platformOperator.fullname" . }}-upgrade
  namespace: {{ .Release.Namespace }}
