name: Release

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: write
  packages: write

jobs:
  publish_image:
    name: Publish Image
    runs-on: ubuntu-latest
    concurrency: release_image
    outputs:
      tag: ${{ steps.release.outputs.tag }}
      version: ${{ steps.release.outputs.version }}
      skip: ${{ steps.release.outputs.skip }}
    steps:
    - name: Purge old artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        expire-in: 30mins
    - name: Release image
      id: release
      uses: neuro-inc/release-image-action@v21.9.36
      with:
        image: platform-operator-controller
        token: ${{ secrets.GH_TOKEN }}
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0
    - name: Github Release
      if: ${{ ! steps.release.outputs.skip }}
      run: |
        if [[ -n $PRERELEASE ]]; then
          gh release create "$TAG" --prerelease --notes "docker pull ghcr.io/neuro-inc/platformsecrets:$VERSION"
        else
          gh release create "$TAG" --notes "docker pull ghcr.io/neuro-inc/platformsecrets:$VERSION"
        fi
      shell: bash
      env:
        TAG: ${{ steps.release.outputs.tag }}
        VERSION: ${{ steps.release.outputs.version }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PRERELEASE: ${{ steps.release.outputs.prerelease }}
